# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sharno
tagline:          'A misfit blog'
description:      'A research assistant at Istanul Sehir University <a href="http://sharno.github.io" target="_blank">sharno</a>.'
url:              http://sharno.github.io
baseurl:          /

author:
  name:           'Mohamed Elsharnouby'
  url:            https://twitter.com/sharno3

paginate:         5

# Custom vars
# version:          2.1.0

#github:
#  repo:           https://github.com/sharno/sharno.github.io
