# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            sharno
tagline:          'A misfit blog'
description:      'A research assistant at Istanul Sehir University <a href="https://twitter.com/sharno3" target="_blank">sharno3</a>.'
url:              http://sharno.me
baseurl:          /

author:
  name:           'Mohamed Elsharnouby'
  url:            https://twitter.com/sharno3

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/sharno/sharno.me
